version: "1.0"
info:
  model: int-scaffold
packages:
- name: KMAT_BRAHProject
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm/KMAT_BRAHProject
  gitUsername: karthikbm
  gitBranch: main
- name: OriginKMAT_Jun2024
  version: "1.0"
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
- name: ApiClient
  version: "1.0"
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
services:
- serviceName: project.kmat_brah.integrations:SF_QueryAccounts
  packages:
  - name: KMAT_BRAHProject
    version: "1.0"
  - name: ApiClient
    version: "1.0"
  - name: OriginKMAT_Jun2024
    version: "1.0"
- serviceName: SF_CCS:SF_DEV_QueryAccounts
  packages:
  - name: OriginKMAT_Jun2024
    version: "1.0"
- serviceName: project.kmat_brah.integrations:UpdateAgentManifest
  packages:
  - name: KMAT_BRAHProject
    version: "1.0"
  - name: ApiClient
    version: "1.0"
  - name: OriginKMAT_Jun2024
    version: "1.0"
- serviceName: test:TestApi
  packages:
  - name: ApiClient
    version: "1.0"
